package com.banking.system.transaction.domain.model.value_object;

import java.util.Objects;
import java.util.UUID;
import java.util.regex.Pattern;

/**
 * Value Object representing an idempotency key for transfer operations.
 * <p>
 * An idempotency key ensures that a transfer operation is only executed once,
 * even if the client retries the request multiple times (due to network failures,
 * timeouts, etc.). The key is generated by the client and must be unique per operation.
 * </p>
 * <p>
 * Format: UUID v4 (e.g., "550e8400-e29b-41d4-a716-446655440000")
 * </p>
 */
public record IdempotencyKey(String value) {

    private static final Pattern UUID_PATTERN = Pattern.compile(
            "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
    );

    public IdempotencyKey {
        Objects.requireNonNull(value, "Idempotency key cannot be null");

        if (value.isBlank()) {
            throw new IllegalArgumentException("Idempotency key cannot be blank");
        }

        if (!UUID_PATTERN.matcher(value).matches()) {
            throw new IllegalArgumentException(
                    "Invalid idempotency key format. Expected UUID format, got: " + value
            );
        }
    }

    /**
     * Creates an IdempotencyKey from a UUID.
     *
     * @param uuid the UUID to use as key
     * @return a new IdempotencyKey instance
     */
    public static IdempotencyKey from(UUID uuid) {
        Objects.requireNonNull(uuid, "UUID cannot be null");
        return new IdempotencyKey(uuid.toString());
    }

    /**
     * Creates an IdempotencyKey from a string value.
     * The string must be in valid UUID format.
     *
     * @param value the string value in UUID format
     * @return a new IdempotencyKey instance
     */
    public static IdempotencyKey from(String value) {
        return new IdempotencyKey(value);
    }

    @Override
    public String toString() {
        return value;
    }
}
