package com.banking.system.auth.domain.model;

import com.banking.system.auth.domain.exception.UserIsAlreadyProcessedException;
import com.banking.system.auth.domain.model.enums.UserStatus;
import com.banking.system.auth.domain.model.value_object.Email;
import com.banking.system.auth.domain.model.value_object.Password;
import lombok.*;

import java.util.Objects;
import java.util.UUID;

@Getter
public class User {
    private final UUID id;
    private Email email;
    private Password password;
    private UserStatus status;
    private Role role;
    private boolean twoFactorEnabled;

    private User(UUID id, Email email, Password password, UserStatus status, Role role, boolean twoFactorEnabled) {
        Objects.requireNonNull(email, "email cannot be null");
        Objects.requireNonNull(password, "password cannot be null");
        Objects.requireNonNull(status, "status cannot be null");
        Objects.requireNonNull(role, "role cannot be null");

        this.id = id;
        this.email = email;
        this.password = password;
        this.status = status;
        this.role = role;
        this.twoFactorEnabled = twoFactorEnabled;
    }

    /**
     * Factory method for creating a new user aggregate from the application layer.
     * <p>
     * This method should be used when registering a brand new user that does not
     * yet exist in the persistence layer. It intentionally sets the {@code id}
     * to {@code null} so that the persistence mechanism can generate it, and
     * initializes the user in the {@link UserStatus#PENDING_VERIFICATION} state.
     * </p>
     *
     * @param email    {@link Email} value object containing a validated email address (must not be {@code null})
     * @param password {@link Password} value object containing an already hashed password (must not be {@code null})
     * @param role     the {@link Role} to assign to this user (must not be {@code null})
     * @return a new {@link User} instance representing a non-persisted user awaiting verification
     */
    public static User createNew(Email email, Password password, Role role) {
        return new User(
                null,
                email,
                password,
                UserStatus.PENDING_VERIFICATION,
                role,
                false
        );
    }

    /**
     * Factory method for reconstituting an existing user aggregate from persistence.
     * <p>
     * This should be used by repository implementations when loading a user
     * from the database. All fields, including {@code id}, {@code status} and
     * {@code role}, are expected to come from a trusted source (e.g. JPA entity,
     * database row) and represent the current state of the user.
     * </p>
     *
     * @param id               unique identifier that has already been generated by the persistence layer
     * @param email            {@link Email} value object reconstituted from the persisted email address
     * @param password         {@link Password} value object reconstituted from the persisted hashed password
     * @param status           current lifecycle status of the user
     * @param role             current role assigned to the user
     * @param twoFactorEnabled whether two-factor authentication is enabled for this user
     * @return a fully initialized {@link User} instance representing an existing user
     */
    public static User reconstitute(UUID id, Email email, Password password, UserStatus status,
                                     Role role, boolean twoFactorEnabled) {
        return new User(
                id,
                email,
                password,
                status,
                role,
                twoFactorEnabled
        );
    }

    // Is necessary verifies thats password is not null because the VO only validates the content
    public void changePassword(Password newPassword) {
        Objects.requireNonNull(newPassword, "newPassword cannot be null");
        this.password = newPassword;
    }

    public void activate() {
        if (this.status != UserStatus.PENDING_VERIFICATION)
            throw new UserIsAlreadyProcessedException("Only users with PENDING_VERIFICATION status can be activated");

        this.status = UserStatus.ACTIVE;
    }

    public void block() {
        if (this.status != UserStatus.ACTIVE)
            throw new UserIsAlreadyProcessedException("Only ACTIVE users can be blocked");

        this.status = UserStatus.BLOCKED;
    }

    public void unblock() {
        if (this.status != UserStatus.BLOCKED)
            throw new UserIsAlreadyProcessedException("Only BLOCKED users can be unblocked");

        this.status = UserStatus.ACTIVE;
    }

    public void deactivate() {
        if (this.status != UserStatus.ACTIVE)
            throw new UserIsAlreadyProcessedException("Only ACTIVE users can deactivate their account");

        this.status = UserStatus.DEACTIVATED;
    }

    public void enableTwoFactor() {
        if (this.status != UserStatus.ACTIVE)
            throw new UserIsAlreadyProcessedException("Only ACTIVE users can enable two-factor authentication");

        this.twoFactorEnabled = true;
    }

    public void disableTwoFactor() {
        this.twoFactorEnabled = false;
    }
}
